### ISSUE TITLE
Change default desktop environment(Not really an issue)

### ISSUE THREAD

**Issue by Peng1029** [iwamatsu/slim#13]
So i recently switched from the Budgie login manager which ever one it has to this one because this one because it loads faster how ever,
 when I start up my laptop it always defaults to gnome which fry's my laptop instantly making it overheat how can I make that be the budgie desktop envirment on startup so I don't fry my laptop,where the budgie login manger always started with budgie

**Comment by RobPearce** [comment]
The default desktop is defined in the /etc/slim.conf file, which the user is expected to configure to their requirements.
